services:
  sql:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
        ACCEPT_EULA: "1"
        MSSQL_SA_PASSWORD: "Password@1"
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    command: start-dev
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - keycloak_data:/opt/keycloak/data
    restart: unless-stopped

volumes:
  redis-data:
  sql-data:
  keycloak_data:
