name: CI – Lint, Build & Test

on:
  # Run on pull requests *targeting* develop
  pull_request:
    branches: [ "develop" ]
  # Run on direct pushes to main (e.g., after PR is merged)
  push:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ../devops-lab-app
    strategy:
      matrix:
        dotnet-version: ['8.0.x']
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Lint (dotnet format)
      run: dotnet format devops-lab-app.sln --verify-no-changes --severity error

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test --no-build --configuration Release --logger:"trx;LogFileName=test-results.trx"
